name: build

on:
  push:
    branches:
      - "master"
      - "ci-*"
    tags:
      - "**"
  pull_request:

env:
  PY_COLORS: 1

jobs:
  tests-py:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.9"
          - "3.10"
          - "3.11"
          - "pypy-3.10"
          - "pypy-3.11"
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install tox
      - name: Run tests
        run: tox run -e py

  tests-misc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - build
          - format
          - generate-integration-files
          - lint
          - type
    steps:
      - uses: actions/checkout@v5
        with:
          # build env: fetch all commits for version computation
          fetch-depth: ${{ matrix.env == 'build' && '0' || '1' }}
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install tox
      - name: Run ${{ matrix.env }}
        run: tox run -e ${{ matrix.env }}
      - if: ${{ matrix.env == 'build' }}
        name: Save ${{ matrix.env }} artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.env }}
          path: dist

  publish:
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - tests-py
      - tests-misc
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write # This permission is mandatory for trusted publishing
    steps:
      - name: Restore build artifacts
        uses: actions/download-artifact@v5
        with:
          name: build
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
